# Generated by Django 4.2.1 on 2023-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='assests/favicon/%Y/%m'),
        ),
    ]
